dist: trusty

matrix:
  exclude:
    - os: linux
  include:
    - os: linux
      env: FLAVOR=linux CXX=g++ BUILDTYPE=Release
    - os: linux
      env: FLAVOR=linux CXX=clang++ BUILDTYPE=Debug
    - os: linux
      env: FLAVOR=linux CXX=clang++ BUILDTYPE=Release
    - os: linux
      env: FLAVOR=android ANDROID_ABI=arm-v7 BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra
    - os: linux
      env: FLAVOR=android ANDROID_ABI=arm-v7 BUILDTYPE=Debug
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra
    - os: linux
      env: FLAVOR=android ANDROID_ABI=arm-v8 BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra
    - os: linux
      env: FLAVOR=android ANDROID_ABI=x86 BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra
    - os: linux
      env: FLAVOR=android ANDROID_ABI=mips BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra

before_install:
- ./scripts/${FLAVOR}/install.sh

script:
- ./scripts/${FLAVOR}/run.sh

git:
  submodules: false
