dist: trusty

matrix:
  exclude:
    - os: linux
  include:
    - os: linux
      env: FLAVOR=linux CXX=g++ BUILDTYPE=Release
    - os: linux
      env: FLAVOR=linux CXX=clang++ BUILDTYPE=Debug
    - os: linux
      env: FLAVOR=linux CXX=clang++ BUILDTYPE=Release
    - os: linux
      env: FLAVOR=android ANDROID_ABIS="arm-v7 arm-v8" BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra
    - os: linux
      env: FLAVOR=android ANDROID_ABIS="x86 x86-64" BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra
    - os: linux
      env: FLAVOR=android ANDROID_ABIS="mips mips-64" BUILDTYPE=Release
      android:
        components:
          - build-tools-22.0.0
          - android-22
          - extra

before_install:
- ./scripts/${FLAVOR}/install.sh

script:
- ./scripts/${FLAVOR}/run.sh

git:
  submodules: false
